---
- name: configuring Nginx repository
  copy:
    dest: /etc/yum.repos.d/nginx.repo
    content: |
      [nginx]
      name=nginx repo
      baseurl=http://nginx.org/packages/centos/7/$basearch/
      gpgcheck=0
      enabled=1

- name: installing http server
  yum:
    name: nginx
    state: installed

- name: remove default http server config file
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: setting permissive mode for SELinux
  selinux:
    policy: targeted
    state: permissive
