---
- include_role:
    name: http_server_stop

- name: creating file repository directory
  file:
    dest: "{{ repositories_dir }}/{{ name }}"
    state: directory

- name: configuring file repository http access
  template:
    src: repository.conf.j2
    dest: /etc/nginx/conf.d/{{ name }}.conf
  vars:
    port: "{{ port }}"
    directory: "{{ repositories_dir }}/{{ name }}"

- include_role:
    name: http_server_start

- include_role:
    name: open_firewall_port
  vars:
    port: "{{ port }}"
