---
- name: configuring Nginx repository
  copy:
    dest: /etc/yum.repos.d/nginx.repo
    content: |
      [nginx]
      name=nginx repo
      baseurl=http://nginx.org/packages/centos/7/$basearch/
      gpgcheck=0
      enabled=1

- name: installing http server
  yum:
    name: nginx
    state: installed

- name: remove default http server config file
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: creating directory for ssl
  file: path=/etc/nginx/ssl state=directory

- name: setting up SSL certifcate
  copy: content={{ nginx_cert }} dest=/etc/nginx/ssl/nginx.crt force=yes

- name: setting up private key
  copy: content={{ nginx_private_key }} dest=/etc/nginx/ssl/nginx.key force=yes

- name: setting up DHE parameter
  shell: '[ -f /etc/nginx/ssl/dhparam.pem ] || openssl dhparam -out /etc/nginx/ssl/dhparam.pem 1024'
